### ISSUE TITLE
Database logic in the service layer

### ISSUE THREAD

**Issue by Luke-Clements** [CECS-491A/core#12]
Having the database logic in the service layer how it currently is means that the code will not be reusable with anything other than entity framework. The DAL should have this functionality, and the service layer should get an instance of the DAO that is needed and then use the functionality attached to that DAO.

Problem(there may be other places as well):
https://github.com/CECS-491A/core/blob/refactor-architecture-backend/Backend/ServiceLayer/Services/UserService.cs

Example:
https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions-1/models-data/validating-with-a-service-layer-cs#decoupling-the-service-layer

**Comment by alfredovargasjr** [comment]
hmm you have a point there.

**Comment by alfredovargasjr** [comment]
i've been thinking alot about the repository pattern, but the more read about it it seems like it is not need cause ef6 provides alot of that funtionality. But it can still be used to isolate the db context between operations and entities using it. I'll look more into it.
